<a href="https://colab.research.google.com/github/MaggieHDez/ClassFiles/blob/main/practica4_MCHD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Práctica 4. Manipulación de matrices**
>**Alumno:** Margarita Cristina Hernández Delgadillo\
>**Matrícula:** 255879

En esta práctica se crearon dos matrices de 3x3 con números aleatorios entre 1 y 10.

Después de esto, se realizaron las siguientes operaciones:

- Sumar ambas matrices.
- Restar la segunda matriz de la primera.
- Multiplicar la primera matriz por 2.
- Realiza una multiplicación matricial entre las dos matrices.

# Creación de Matrices

In [6]:
import numpy as np

matA = np.random.randint(1, 11, size=(3, 3))
matB = np.random.randint(1, 11, size=(3, 3))

# Cálculos realizados

In [10]:
print("Matriz A:")
print(matA)
print("\nMatriz B:")
print(matB)
print("\n****************************************")
print("Suma de las matrices:\n",matA + matB)
print("\n****************************************")
print("Resta de las matrices:\n", matA - matB)
print("\n****************************************")
print("Multiplicación de la matriz A por 2:\n", matA * 2)
print("\n****************************************")
print("Multiplicación matricial:\n", np.dot(matA, matB))

Matriz A:
[[ 6 10  5]
 [ 1  1  2]
 [ 8  9  9]]

Matriz B:
[[ 1  8 10]
 [ 4  9  1]
 [10  5  2]]

****************************************
Suma de las matrices:
 [[ 7 18 15]
 [ 5 10  3]
 [18 14 11]]

****************************************
Resta de las matrices:
 [[ 5  2 -5]
 [-3 -8  1]
 [-2  4  7]]

****************************************
Multiplicación de la matriz A por 2:
 [[12 20 10]
 [ 2  2  4]
 [16 18 18]]

****************************************
Multiplicación matricial:
 [[ 96 163  80]
 [ 25  27  15]
 [134 190 107]]
